### ISSUE TITLE
get_version() can't access version

### ISSUE THREAD

**Issue by a7p** [pypa/setuptools_scm#8]
I'm calling get_version() in an installed module.
The interpreter is invoked via ```/<path_to_venv>/python -m module.app```.
pip freeze show's the version correctly, I'm using a git repo, the app was installed via pip install ssh+git...

**Comment by RonnyPfannschmidt** [comment]
get_version is intended to be used in repos/sdists, for installed versions the metadata is availiable via the package installer metadata

**Comment by RonnyPfannschmidt** [comment]
for clarification - use pkg_ressources.get_distribution('mymodule').version

**Comment by a7p** [comment]
Thank you very much for the quick and helpful answer.
